# Generated by Django 2.0.7 on 2018-07-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('tech_1', models.IntegerField(default=10)),
                ('tech_2', models.IntegerField(default=20)),
                ('tech_3', models.IntegerField(default=30)),
                ('tech_4', models.IntegerField(default=40)),
                ('tech_5', models.IntegerField(default=50)),
                ('tech_6', models.IntegerField(default=60)),
            ],
        ),
    ]
